; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
lib_ldf_mode = deep+
build_flags = 
	-Iinclude/capabilities/
	-Iinclude/components/
	-Iinclude/simulation/

[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = arduino
monitor_speed = 115200
upload_protocol = serial
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.2
	adafruit/Adafruit ADXL345@^1.3.4
	adafruit/Adafruit BNO08x@^1.2.5
	adafruit/Adafruit BMP5xx Library@^1.0.2
	arduino-libraries/SD@^1.3.0
	Servo
build_flags = ${env.build_flags}
	-D NUCLEO_F446RE_PLATFORM