#pragma once

/* DEFINE FOR TARGET APOGEE OF ACE (IN METERS) */
#define ACE_TARGET_APOGEE 1341.12
#define MAX_ALT_CHANGE 100
// Uncomment for launch
// #define ACE_TARGET_APOGEE 950
// #define MAX_ALT_CHANGE 100
#define ACE_SHUTOFF_THRESHOLD (ACE_TARGET_APOGEE-60) // Calibrate later if necessary

/* DEFINE FOR DEVELOPMENT MODE OF ACE (ENABLES DEBUG PRINTS AND SIMULATION) */
#define IS_DEVELOPMENT_MODE 0

#define RUN_SIMULATION 0

/* DEFINE FOR STRICT INITIALIZATION CHECKS (REQUIRES FULL INIT TO BEGIN) */
#define CHECK_STRICT_INITIALIZATION 1

/* DEFINE FOR PERFORMING PHYSICAL SERVO ACTUATION TEST AT INIT */
#define DO_SERVO_ACTUATE_INIT_CHECK 1

/* DEFINE FOR DISABLING FAULT PROTECTION FOR TESTING PURPOSES*/
#define DISABLE_FAULT_PROTECTION 0

/* DEFINE FOR NUMER OF CYCLES OF AUTOMATIC EXTENSION UPON ENTERING CONTROL (0 is none)*/
#define FORCED_EXTENSION_CONTROL_CYCLES 0

/* DEFINE FOR STATUS LED */
#define ENABLE_STATUS_LED 0

/* DEFINE FOR INVERTING AIRBRAKES SERVO MOVEMENT*/
#define SERVO_INVERTED 1

/* DEFINE FOR USING ORIENTATION TO CORRECT ACCELERATION (DEDICATED ACCELEROMETER)*/
#define CORRECT_ACCEL 0

/* DEFINE FOR MAX ALTITUDE RANGE PERMITTED BEFORE INITIALIZING ALTIMITER FAULT PROTECTION*/
#define MAX_ALT_RANGE_FAULT_PROTECTION 10